run:
  timeout: 2m

output:
  formats:
    - format: colored-line-number

linters-settings:
  dupl:
    threshold: 100
  errcheck:
    check-type-assertions: true
    check-blank: true
  exhaustive:
    default-signifies-exhaustive: true
  gci:
    sections:
      - standard
      - default
      - prefix(github.com/heartandu/easyrpc)
  gocognit:
    min-complexity: 20
  goconst:
    min-occurrences: 2
    ignore-tests: true
  gocritic:
    enabled-tags:
      - diagnostic
      - style
      - performance
      - experimental
      - opinionated
  gocyclo:
    min-complexity: 20
  goimports:
    local-prefixes: github.com/heartandu/easyrpc
  govet:
    enable-all: true
    disable:
      - fieldalignment
  nlreturn:
    block-size: 2
  revive:
    ignore-generated-header: true
    enable-all-rules: true
    rules:
      - name: line-length-limit
        arguments: [120]
      - name: deep-exit
        disabled: true
      - name: add-constant
        arguments:
          - maxLitCount: "3"
            allowStrs: '""'
            allowInts: "0,1,2"
            allowFloats: "0.0,0.,1.0,1.,2.0,2."
      - name: cognitive-complexity
        arguments: [20]
      - name: unhandled-error
        arguments:
          - fmt.Fprintln
          - fmt.Fprintf
  tagalign:
    sort: false
  testifylint:
    enable-all: true

linters:
  enable-all: true
  disable:
    - depguard
    - exhaustruct
    - execinquery
    - ireturn
    - gomnd

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - dupl
        - err113
        - errcheck
        - gocyclo
        - gosec
