// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: types/types.proto

package types

import (
	common "github.com/heartandu/easyrpc/internal/testdata/proto/types/common"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Enums
type Status int32

const (
	Status_UNKNOWN   Status = 0
	Status_PENDING   Status = 1
	Status_RUNNING   Status = 2
	Status_COMPLETED Status = 3
	Status_FAILED    Status = 4
)

// Enum value maps for Status.
var (
	Status_name = map[int32]string{
		0: "UNKNOWN",
		1: "PENDING",
		2: "RUNNING",
		3: "COMPLETED",
		4: "FAILED",
	}
	Status_value = map[string]int32{
		"UNKNOWN":   0,
		"PENDING":   1,
		"RUNNING":   2,
		"COMPLETED": 3,
		"FAILED":    4,
	}
)

func (x Status) Enum() *Status {
	p := new(Status)
	*p = x
	return p
}

func (x Status) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Status) Descriptor() protoreflect.EnumDescriptor {
	return file_types_types_proto_enumTypes[0].Descriptor()
}

func (Status) Type() protoreflect.EnumType {
	return &file_types_types_proto_enumTypes[0]
}

func (x Status) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Status.Descriptor instead.
func (Status) EnumDescriptor() ([]byte, []int) {
	return file_types_types_proto_rawDescGZIP(), []int{0}
}

type Priority int32

const (
	Priority_LOW      Priority = 0
	Priority_MEDIUM   Priority = 1
	Priority_HIGH     Priority = 2
	Priority_CRITICAL Priority = 3
)

// Enum value maps for Priority.
var (
	Priority_name = map[int32]string{
		0: "LOW",
		1: "MEDIUM",
		2: "HIGH",
		3: "CRITICAL",
	}
	Priority_value = map[string]int32{
		"LOW":      0,
		"MEDIUM":   1,
		"HIGH":     2,
		"CRITICAL": 3,
	}
)

func (x Priority) Enum() *Priority {
	p := new(Priority)
	*p = x
	return p
}

func (x Priority) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Priority) Descriptor() protoreflect.EnumDescriptor {
	return file_types_types_proto_enumTypes[1].Descriptor()
}

func (Priority) Type() protoreflect.EnumType {
	return &file_types_types_proto_enumTypes[1]
}

func (x Priority) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Priority.Descriptor instead.
func (Priority) EnumDescriptor() ([]byte, []int) {
	return file_types_types_proto_rawDescGZIP(), []int{1}
}

// Scalar types - all protobuf scalar types
type ScalarTypes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DoubleField   float64                `protobuf:"fixed64,1,opt,name=double_field,json=doubleField,proto3" json:"double_field,omitempty"`
	FloatField    float32                `protobuf:"fixed32,2,opt,name=float_field,json=floatField,proto3" json:"float_field,omitempty"`
	Int32Field    int32                  `protobuf:"varint,3,opt,name=int32_field,json=int32Field,proto3" json:"int32_field,omitempty"`
	Int64Field    int64                  `protobuf:"varint,4,opt,name=int64_field,json=int64Field,proto3" json:"int64_field,omitempty"`
	Uint32Field   uint32                 `protobuf:"varint,5,opt,name=uint32_field,json=uint32Field,proto3" json:"uint32_field,omitempty"`
	Uint64Field   uint64                 `protobuf:"varint,6,opt,name=uint64_field,json=uint64Field,proto3" json:"uint64_field,omitempty"`
	Sint32Field   int32                  `protobuf:"zigzag32,7,opt,name=sint32_field,json=sint32Field,proto3" json:"sint32_field,omitempty"`
	Sint64Field   int64                  `protobuf:"zigzag64,8,opt,name=sint64_field,json=sint64Field,proto3" json:"sint64_field,omitempty"`
	Fixed32Field  uint32                 `protobuf:"fixed32,9,opt,name=fixed32_field,json=fixed32Field,proto3" json:"fixed32_field,omitempty"`
	Fixed64Field  uint64                 `protobuf:"fixed64,10,opt,name=fixed64_field,json=fixed64Field,proto3" json:"fixed64_field,omitempty"`
	Sfixed32Field int32                  `protobuf:"fixed32,11,opt,name=sfixed32_field,json=sfixed32Field,proto3" json:"sfixed32_field,omitempty"`
	Sfixed64Field int64                  `protobuf:"fixed64,12,opt,name=sfixed64_field,json=sfixed64Field,proto3" json:"sfixed64_field,omitempty"`
	BoolField     bool                   `protobuf:"varint,13,opt,name=bool_field,json=boolField,proto3" json:"bool_field,omitempty"`
	StringField   string                 `protobuf:"bytes,14,opt,name=string_field,json=stringField,proto3" json:"string_field,omitempty"`
	BytesField    []byte                 `protobuf:"bytes,15,opt,name=bytes_field,json=bytesField,proto3" json:"bytes_field,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ScalarTypes) Reset() {
	*x = ScalarTypes{}
	mi := &file_types_types_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScalarTypes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScalarTypes) ProtoMessage() {}

func (x *ScalarTypes) ProtoReflect() protoreflect.Message {
	mi := &file_types_types_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScalarTypes.ProtoReflect.Descriptor instead.
func (*ScalarTypes) Descriptor() ([]byte, []int) {
	return file_types_types_proto_rawDescGZIP(), []int{0}
}

func (x *ScalarTypes) GetDoubleField() float64 {
	if x != nil {
		return x.DoubleField
	}
	return 0
}

func (x *ScalarTypes) GetFloatField() float32 {
	if x != nil {
		return x.FloatField
	}
	return 0
}

func (x *ScalarTypes) GetInt32Field() int32 {
	if x != nil {
		return x.Int32Field
	}
	return 0
}

func (x *ScalarTypes) GetInt64Field() int64 {
	if x != nil {
		return x.Int64Field
	}
	return 0
}

func (x *ScalarTypes) GetUint32Field() uint32 {
	if x != nil {
		return x.Uint32Field
	}
	return 0
}

func (x *ScalarTypes) GetUint64Field() uint64 {
	if x != nil {
		return x.Uint64Field
	}
	return 0
}

func (x *ScalarTypes) GetSint32Field() int32 {
	if x != nil {
		return x.Sint32Field
	}
	return 0
}

func (x *ScalarTypes) GetSint64Field() int64 {
	if x != nil {
		return x.Sint64Field
	}
	return 0
}

func (x *ScalarTypes) GetFixed32Field() uint32 {
	if x != nil {
		return x.Fixed32Field
	}
	return 0
}

func (x *ScalarTypes) GetFixed64Field() uint64 {
	if x != nil {
		return x.Fixed64Field
	}
	return 0
}

func (x *ScalarTypes) GetSfixed32Field() int32 {
	if x != nil {
		return x.Sfixed32Field
	}
	return 0
}

func (x *ScalarTypes) GetSfixed64Field() int64 {
	if x != nil {
		return x.Sfixed64Field
	}
	return 0
}

func (x *ScalarTypes) GetBoolField() bool {
	if x != nil {
		return x.BoolField
	}
	return false
}

func (x *ScalarTypes) GetStringField() string {
	if x != nil {
		return x.StringField
	}
	return ""
}

func (x *ScalarTypes) GetBytesField() []byte {
	if x != nil {
		return x.BytesField
	}
	return nil
}

type EnumTypes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        Status                 `protobuf:"varint,1,opt,name=status,proto3,enum=types.Status" json:"status,omitempty"`
	Priority      Priority               `protobuf:"varint,2,opt,name=priority,proto3,enum=types.Priority" json:"priority,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EnumTypes) Reset() {
	*x = EnumTypes{}
	mi := &file_types_types_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnumTypes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnumTypes) ProtoMessage() {}

func (x *EnumTypes) ProtoReflect() protoreflect.Message {
	mi := &file_types_types_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnumTypes.ProtoReflect.Descriptor instead.
func (*EnumTypes) Descriptor() ([]byte, []int) {
	return file_types_types_proto_rawDescGZIP(), []int{1}
}

func (x *EnumTypes) GetStatus() Status {
	if x != nil {
		return x.Status
	}
	return Status_UNKNOWN
}

func (x *EnumTypes) GetPriority() Priority {
	if x != nil {
		return x.Priority
	}
	return Priority_LOW
}

// Maps
type Maps struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	StringToInt     map[string]int32       `protobuf:"bytes,1,rep,name=string_to_int,json=stringToInt,proto3" json:"string_to_int,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	IntToString     map[int64]string       `protobuf:"bytes,2,rep,name=int_to_string,json=intToString,proto3" json:"int_to_string,omitempty" protobuf_key:"varint,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	StringToMessage map[string]*Maps_Inner `protobuf:"bytes,3,rep,name=string_to_message,json=stringToMessage,proto3" json:"string_to_message,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	BoolToFloat     map[bool]float32       `protobuf:"bytes,4,rep,name=bool_to_float,json=boolToFloat,proto3" json:"bool_to_float,omitempty" protobuf_key:"varint,1,opt,name=key" protobuf_val:"fixed32,2,opt,name=value"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *Maps) Reset() {
	*x = Maps{}
	mi := &file_types_types_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Maps) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Maps) ProtoMessage() {}

func (x *Maps) ProtoReflect() protoreflect.Message {
	mi := &file_types_types_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Maps.ProtoReflect.Descriptor instead.
func (*Maps) Descriptor() ([]byte, []int) {
	return file_types_types_proto_rawDescGZIP(), []int{2}
}

func (x *Maps) GetStringToInt() map[string]int32 {
	if x != nil {
		return x.StringToInt
	}
	return nil
}

func (x *Maps) GetIntToString() map[int64]string {
	if x != nil {
		return x.IntToString
	}
	return nil
}

func (x *Maps) GetStringToMessage() map[string]*Maps_Inner {
	if x != nil {
		return x.StringToMessage
	}
	return nil
}

func (x *Maps) GetBoolToFloat() map[bool]float32 {
	if x != nil {
		return x.BoolToFloat
	}
	return nil
}

// Oneofs
type Oneof struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Choice:
	//
	//	*Oneof_Text
	//	*Oneof_Number
	//	*Oneof_Flag
	//	*Oneof_Inner_
	Choice        isOneof_Choice `protobuf_oneof:"choice"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Oneof) Reset() {
	*x = Oneof{}
	mi := &file_types_types_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Oneof) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Oneof) ProtoMessage() {}

func (x *Oneof) ProtoReflect() protoreflect.Message {
	mi := &file_types_types_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Oneof.ProtoReflect.Descriptor instead.
func (*Oneof) Descriptor() ([]byte, []int) {
	return file_types_types_proto_rawDescGZIP(), []int{3}
}

func (x *Oneof) GetChoice() isOneof_Choice {
	if x != nil {
		return x.Choice
	}
	return nil
}

func (x *Oneof) GetText() string {
	if x != nil {
		if x, ok := x.Choice.(*Oneof_Text); ok {
			return x.Text
		}
	}
	return ""
}

func (x *Oneof) GetNumber() int32 {
	if x != nil {
		if x, ok := x.Choice.(*Oneof_Number); ok {
			return x.Number
		}
	}
	return 0
}

func (x *Oneof) GetFlag() bool {
	if x != nil {
		if x, ok := x.Choice.(*Oneof_Flag); ok {
			return x.Flag
		}
	}
	return false
}

func (x *Oneof) GetInner() *Oneof_Inner {
	if x != nil {
		if x, ok := x.Choice.(*Oneof_Inner_); ok {
			return x.Inner
		}
	}
	return nil
}

type isOneof_Choice interface {
	isOneof_Choice()
}

type Oneof_Text struct {
	Text string `protobuf:"bytes,1,opt,name=text,proto3,oneof"`
}

type Oneof_Number struct {
	Number int32 `protobuf:"varint,2,opt,name=number,proto3,oneof"`
}

type Oneof_Flag struct {
	Flag bool `protobuf:"varint,3,opt,name=flag,proto3,oneof"`
}

type Oneof_Inner_ struct {
	Inner *Oneof_Inner `protobuf:"bytes,4,opt,name=inner,proto3,oneof"`
}

func (*Oneof_Text) isOneof_Choice() {}

func (*Oneof_Number) isOneof_Choice() {}

func (*Oneof_Flag) isOneof_Choice() {}

func (*Oneof_Inner_) isOneof_Choice() {}

// Nested messages - uses common types
type Imported struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Imported      *common.Imported       `protobuf:"bytes,1,opt,name=imported,proto3" json:"imported,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Imported) Reset() {
	*x = Imported{}
	mi := &file_types_types_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Imported) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Imported) ProtoMessage() {}

func (x *Imported) ProtoReflect() protoreflect.Message {
	mi := &file_types_types_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Imported.ProtoReflect.Descriptor instead.
func (*Imported) Descriptor() ([]byte, []int) {
	return file_types_types_proto_rawDescGZIP(), []int{4}
}

func (x *Imported) GetImported() *common.Imported {
	if x != nil {
		return x.Imported
	}
	return nil
}

// Recursive messages - uses common types
type RecursiveNode struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         string                 `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	Child         *RecursiveNode         `protobuf:"bytes,2,opt,name=child,proto3" json:"child,omitempty"`
	Children      []*RecursiveNode       `protobuf:"bytes,3,rep,name=children,proto3" json:"children,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RecursiveNode) Reset() {
	*x = RecursiveNode{}
	mi := &file_types_types_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RecursiveNode) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecursiveNode) ProtoMessage() {}

func (x *RecursiveNode) ProtoReflect() protoreflect.Message {
	mi := &file_types_types_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecursiveNode.ProtoReflect.Descriptor instead.
func (*RecursiveNode) Descriptor() ([]byte, []int) {
	return file_types_types_proto_rawDescGZIP(), []int{5}
}

func (x *RecursiveNode) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

func (x *RecursiveNode) GetChild() *RecursiveNode {
	if x != nil {
		return x.Child
	}
	return nil
}

func (x *RecursiveNode) GetChildren() []*RecursiveNode {
	if x != nil {
		return x.Children
	}
	return nil
}

type Recursive struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Node          *RecursiveNode         `protobuf:"bytes,1,opt,name=node,proto3" json:"node,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Recursive) Reset() {
	*x = Recursive{}
	mi := &file_types_types_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Recursive) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Recursive) ProtoMessage() {}

func (x *Recursive) ProtoReflect() protoreflect.Message {
	mi := &file_types_types_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Recursive.ProtoReflect.Descriptor instead.
func (*Recursive) Descriptor() ([]byte, []int) {
	return file_types_types_proto_rawDescGZIP(), []int{6}
}

func (x *Recursive) GetNode() *RecursiveNode {
	if x != nil {
		return x.Node
	}
	return nil
}

// Optional fields (proto3 optional)
type Optional struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	OptionalString *string                `protobuf:"bytes,1,opt,name=optional_string,json=optionalString,proto3,oneof" json:"optional_string,omitempty"`
	OptionalInt32  *int32                 `protobuf:"varint,2,opt,name=optional_int32,json=optionalInt32,proto3,oneof" json:"optional_int32,omitempty"`
	OptionalBool   *bool                  `protobuf:"varint,3,opt,name=optional_bool,json=optionalBool,proto3,oneof" json:"optional_bool,omitempty"`
	OptionalInner  *Optional_Inner        `protobuf:"bytes,4,opt,name=optional_inner,json=optionalInner,proto3,oneof" json:"optional_inner,omitempty"`
	OptionalEnum   *Status                `protobuf:"varint,5,opt,name=optional_enum,json=optionalEnum,proto3,enum=types.Status,oneof" json:"optional_enum,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Optional) Reset() {
	*x = Optional{}
	mi := &file_types_types_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Optional) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Optional) ProtoMessage() {}

func (x *Optional) ProtoReflect() protoreflect.Message {
	mi := &file_types_types_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Optional.ProtoReflect.Descriptor instead.
func (*Optional) Descriptor() ([]byte, []int) {
	return file_types_types_proto_rawDescGZIP(), []int{7}
}

func (x *Optional) GetOptionalString() string {
	if x != nil && x.OptionalString != nil {
		return *x.OptionalString
	}
	return ""
}

func (x *Optional) GetOptionalInt32() int32 {
	if x != nil && x.OptionalInt32 != nil {
		return *x.OptionalInt32
	}
	return 0
}

func (x *Optional) GetOptionalBool() bool {
	if x != nil && x.OptionalBool != nil {
		return *x.OptionalBool
	}
	return false
}

func (x *Optional) GetOptionalInner() *Optional_Inner {
	if x != nil {
		return x.OptionalInner
	}
	return nil
}

func (x *Optional) GetOptionalEnum() Status {
	if x != nil && x.OptionalEnum != nil {
		return *x.OptionalEnum
	}
	return Status_UNKNOWN
}

// Repeated fields
type Repeated struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Strings       []string               `protobuf:"bytes,1,rep,name=strings,proto3" json:"strings,omitempty"`
	Integers      []int64                `protobuf:"varint,2,rep,packed,name=integers,proto3" json:"integers,omitempty"`
	Doubles       []float64              `protobuf:"fixed64,3,rep,packed,name=doubles,proto3" json:"doubles,omitempty"`
	Bools         []bool                 `protobuf:"varint,4,rep,packed,name=bools,proto3" json:"bools,omitempty"`
	Statuses      []Status               `protobuf:"varint,5,rep,packed,name=statuses,proto3,enum=types.Status" json:"statuses,omitempty"`
	InnerItems    []*Repeated_Inner      `protobuf:"bytes,6,rep,name=inner_items,json=innerItems,proto3" json:"inner_items,omitempty"`
	BytesList     [][]byte               `protobuf:"bytes,7,rep,name=bytes_list,json=bytesList,proto3" json:"bytes_list,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Repeated) Reset() {
	*x = Repeated{}
	mi := &file_types_types_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Repeated) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Repeated) ProtoMessage() {}

func (x *Repeated) ProtoReflect() protoreflect.Message {
	mi := &file_types_types_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Repeated.ProtoReflect.Descriptor instead.
func (*Repeated) Descriptor() ([]byte, []int) {
	return file_types_types_proto_rawDescGZIP(), []int{8}
}

func (x *Repeated) GetStrings() []string {
	if x != nil {
		return x.Strings
	}
	return nil
}

func (x *Repeated) GetIntegers() []int64 {
	if x != nil {
		return x.Integers
	}
	return nil
}

func (x *Repeated) GetDoubles() []float64 {
	if x != nil {
		return x.Doubles
	}
	return nil
}

func (x *Repeated) GetBools() []bool {
	if x != nil {
		return x.Bools
	}
	return nil
}

func (x *Repeated) GetStatuses() []Status {
	if x != nil {
		return x.Statuses
	}
	return nil
}

func (x *Repeated) GetInnerItems() []*Repeated_Inner {
	if x != nil {
		return x.InnerItems
	}
	return nil
}

func (x *Repeated) GetBytesList() [][]byte {
	if x != nil {
		return x.BytesList
	}
	return nil
}

type Maps_Inner struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Maps_Inner) Reset() {
	*x = Maps_Inner{}
	mi := &file_types_types_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Maps_Inner) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Maps_Inner) ProtoMessage() {}

func (x *Maps_Inner) ProtoReflect() protoreflect.Message {
	mi := &file_types_types_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Maps_Inner.ProtoReflect.Descriptor instead.
func (*Maps_Inner) Descriptor() ([]byte, []int) {
	return file_types_types_proto_rawDescGZIP(), []int{2, 0}
}

func (x *Maps_Inner) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type Oneof_Inner struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Oneof_Inner) Reset() {
	*x = Oneof_Inner{}
	mi := &file_types_types_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Oneof_Inner) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Oneof_Inner) ProtoMessage() {}

func (x *Oneof_Inner) ProtoReflect() protoreflect.Message {
	mi := &file_types_types_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Oneof_Inner.ProtoReflect.Descriptor instead.
func (*Oneof_Inner) Descriptor() ([]byte, []int) {
	return file_types_types_proto_rawDescGZIP(), []int{3, 0}
}

func (x *Oneof_Inner) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type Optional_Inner struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Optional_Inner) Reset() {
	*x = Optional_Inner{}
	mi := &file_types_types_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Optional_Inner) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Optional_Inner) ProtoMessage() {}

func (x *Optional_Inner) ProtoReflect() protoreflect.Message {
	mi := &file_types_types_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Optional_Inner.ProtoReflect.Descriptor instead.
func (*Optional_Inner) Descriptor() ([]byte, []int) {
	return file_types_types_proto_rawDescGZIP(), []int{7, 0}
}

func (x *Optional_Inner) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type Repeated_Inner struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Repeated_Inner) Reset() {
	*x = Repeated_Inner{}
	mi := &file_types_types_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Repeated_Inner) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Repeated_Inner) ProtoMessage() {}

func (x *Repeated_Inner) ProtoReflect() protoreflect.Message {
	mi := &file_types_types_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Repeated_Inner.ProtoReflect.Descriptor instead.
func (*Repeated_Inner) Descriptor() ([]byte, []int) {
	return file_types_types_proto_rawDescGZIP(), []int{8, 0}
}

func (x *Repeated_Inner) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

var File_types_types_proto protoreflect.FileDescriptor

const file_types_types_proto_rawDesc = "" +
	"\n" +
	"\x11types/types.proto\x12\x05types\x1a\x19types/common/common.proto\"\x9a\x04\n" +
	"\vScalarTypes\x12!\n" +
	"\fdouble_field\x18\x01 \x01(\x01R\vdoubleField\x12\x1f\n" +
	"\vfloat_field\x18\x02 \x01(\x02R\n" +
	"floatField\x12\x1f\n" +
	"\vint32_field\x18\x03 \x01(\x05R\n" +
	"int32Field\x12\x1f\n" +
	"\vint64_field\x18\x04 \x01(\x03R\n" +
	"int64Field\x12!\n" +
	"\fuint32_field\x18\x05 \x01(\rR\vuint32Field\x12!\n" +
	"\fuint64_field\x18\x06 \x01(\x04R\vuint64Field\x12!\n" +
	"\fsint32_field\x18\a \x01(\x11R\vsint32Field\x12!\n" +
	"\fsint64_field\x18\b \x01(\x12R\vsint64Field\x12#\n" +
	"\rfixed32_field\x18\t \x01(\aR\ffixed32Field\x12#\n" +
	"\rfixed64_field\x18\n" +
	" \x01(\x06R\ffixed64Field\x12%\n" +
	"\x0esfixed32_field\x18\v \x01(\x0fR\rsfixed32Field\x12%\n" +
	"\x0esfixed64_field\x18\f \x01(\x10R\rsfixed64Field\x12\x1d\n" +
	"\n" +
	"bool_field\x18\r \x01(\bR\tboolField\x12!\n" +
	"\fstring_field\x18\x0e \x01(\tR\vstringField\x12\x1f\n" +
	"\vbytes_field\x18\x0f \x01(\fR\n" +
	"bytesField\"_\n" +
	"\tEnumTypes\x12%\n" +
	"\x06status\x18\x01 \x01(\x0e2\r.types.StatusR\x06status\x12+\n" +
	"\bpriority\x18\x02 \x01(\x0e2\x0f.types.PriorityR\bpriority\"\xca\x04\n" +
	"\x04Maps\x12@\n" +
	"\rstring_to_int\x18\x01 \x03(\v2\x1c.types.Maps.StringToIntEntryR\vstringToInt\x12@\n" +
	"\rint_to_string\x18\x02 \x03(\v2\x1c.types.Maps.IntToStringEntryR\vintToString\x12L\n" +
	"\x11string_to_message\x18\x03 \x03(\v2 .types.Maps.StringToMessageEntryR\x0fstringToMessage\x12@\n" +
	"\rbool_to_float\x18\x04 \x03(\v2\x1c.types.Maps.BoolToFloatEntryR\vboolToFloat\x1a\x17\n" +
	"\x05Inner\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\x1a>\n" +
	"\x10StringToIntEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x05R\x05value:\x028\x01\x1a>\n" +
	"\x10IntToStringEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\x03R\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\x1aU\n" +
	"\x14StringToMessageEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12'\n" +
	"\x05value\x18\x02 \x01(\v2\x11.types.Maps.InnerR\x05value:\x028\x01\x1a>\n" +
	"\x10BoolToFloatEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\bR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x02R\x05value:\x028\x01\"\x9c\x01\n" +
	"\x05Oneof\x12\x14\n" +
	"\x04text\x18\x01 \x01(\tH\x00R\x04text\x12\x18\n" +
	"\x06number\x18\x02 \x01(\x05H\x00R\x06number\x12\x14\n" +
	"\x04flag\x18\x03 \x01(\bH\x00R\x04flag\x12*\n" +
	"\x05inner\x18\x04 \x01(\v2\x12.types.Oneof.InnerH\x00R\x05inner\x1a\x17\n" +
	"\x05Inner\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02idB\b\n" +
	"\x06choice\">\n" +
	"\bImported\x122\n" +
	"\bimported\x18\x01 \x01(\v2\x16.types.common.ImportedR\bimported\"\x83\x01\n" +
	"\rRecursiveNode\x12\x14\n" +
	"\x05value\x18\x01 \x01(\tR\x05value\x12*\n" +
	"\x05child\x18\x02 \x01(\v2\x14.types.RecursiveNodeR\x05child\x120\n" +
	"\bchildren\x18\x03 \x03(\v2\x14.types.RecursiveNodeR\bchildren\"5\n" +
	"\tRecursive\x12(\n" +
	"\x04node\x18\x01 \x01(\v2\x14.types.RecursiveNodeR\x04node\"\x81\x03\n" +
	"\bOptional\x12,\n" +
	"\x0foptional_string\x18\x01 \x01(\tH\x00R\x0eoptionalString\x88\x01\x01\x12*\n" +
	"\x0eoptional_int32\x18\x02 \x01(\x05H\x01R\roptionalInt32\x88\x01\x01\x12(\n" +
	"\roptional_bool\x18\x03 \x01(\bH\x02R\foptionalBool\x88\x01\x01\x12A\n" +
	"\x0eoptional_inner\x18\x04 \x01(\v2\x15.types.Optional.InnerH\x03R\roptionalInner\x88\x01\x01\x127\n" +
	"\roptional_enum\x18\x05 \x01(\x0e2\r.types.StatusH\x04R\foptionalEnum\x88\x01\x01\x1a\x17\n" +
	"\x05Inner\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02idB\x12\n" +
	"\x10_optional_stringB\x11\n" +
	"\x0f_optional_int32B\x10\n" +
	"\x0e_optional_boolB\x11\n" +
	"\x0f_optional_innerB\x10\n" +
	"\x0e_optional_enum\"\x8b\x02\n" +
	"\bRepeated\x12\x18\n" +
	"\astrings\x18\x01 \x03(\tR\astrings\x12\x1a\n" +
	"\bintegers\x18\x02 \x03(\x03R\bintegers\x12\x18\n" +
	"\adoubles\x18\x03 \x03(\x01R\adoubles\x12\x14\n" +
	"\x05bools\x18\x04 \x03(\bR\x05bools\x12)\n" +
	"\bstatuses\x18\x05 \x03(\x0e2\r.types.StatusR\bstatuses\x126\n" +
	"\vinner_items\x18\x06 \x03(\v2\x15.types.Repeated.InnerR\n" +
	"innerItems\x12\x1d\n" +
	"\n" +
	"bytes_list\x18\a \x03(\fR\tbytesList\x1a\x17\n" +
	"\x05Inner\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id*J\n" +
	"\x06Status\x12\v\n" +
	"\aUNKNOWN\x10\x00\x12\v\n" +
	"\aPENDING\x10\x01\x12\v\n" +
	"\aRUNNING\x10\x02\x12\r\n" +
	"\tCOMPLETED\x10\x03\x12\n" +
	"\n" +
	"\x06FAILED\x10\x04*7\n" +
	"\bPriority\x12\a\n" +
	"\x03LOW\x10\x00\x12\n" +
	"\n" +
	"\x06MEDIUM\x10\x01\x12\b\n" +
	"\x04HIGH\x10\x02\x12\f\n" +
	"\bCRITICAL\x10\x032\xf8\x02\n" +
	"\fTypesService\x125\n" +
	"\vScalarTypes\x12\x12.types.ScalarTypes\x1a\x12.types.ScalarTypes\x12/\n" +
	"\tEnumTypes\x12\x10.types.EnumTypes\x1a\x10.types.EnumTypes\x12 \n" +
	"\x04Maps\x12\v.types.Maps\x1a\v.types.Maps\x12#\n" +
	"\x05Oneof\x12\f.types.Oneof\x1a\f.types.Oneof\x12,\n" +
	"\bImported\x12\x0f.types.Imported\x1a\x0f.types.Imported\x12/\n" +
	"\tRecursive\x12\x10.types.Recursive\x1a\x10.types.Recursive\x12,\n" +
	"\bOptional\x12\x0f.types.Optional\x1a\x0f.types.Optional\x12,\n" +
	"\bRepeated\x12\x0f.types.Repeated\x1a\x0f.types.RepeatedB<Z:github.com/heartandu/easyrpc/internal/testdata/proto/typesb\x06proto3"

var (
	file_types_types_proto_rawDescOnce sync.Once
	file_types_types_proto_rawDescData []byte
)

func file_types_types_proto_rawDescGZIP() []byte {
	file_types_types_proto_rawDescOnce.Do(func() {
		file_types_types_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_types_types_proto_rawDesc), len(file_types_types_proto_rawDesc)))
	})
	return file_types_types_proto_rawDescData
}

var file_types_types_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_types_types_proto_msgTypes = make([]protoimpl.MessageInfo, 17)
var file_types_types_proto_goTypes = []any{
	(Status)(0),             // 0: types.Status
	(Priority)(0),           // 1: types.Priority
	(*ScalarTypes)(nil),     // 2: types.ScalarTypes
	(*EnumTypes)(nil),       // 3: types.EnumTypes
	(*Maps)(nil),            // 4: types.Maps
	(*Oneof)(nil),           // 5: types.Oneof
	(*Imported)(nil),        // 6: types.Imported
	(*RecursiveNode)(nil),   // 7: types.RecursiveNode
	(*Recursive)(nil),       // 8: types.Recursive
	(*Optional)(nil),        // 9: types.Optional
	(*Repeated)(nil),        // 10: types.Repeated
	(*Maps_Inner)(nil),      // 11: types.Maps.Inner
	nil,                     // 12: types.Maps.StringToIntEntry
	nil,                     // 13: types.Maps.IntToStringEntry
	nil,                     // 14: types.Maps.StringToMessageEntry
	nil,                     // 15: types.Maps.BoolToFloatEntry
	(*Oneof_Inner)(nil),     // 16: types.Oneof.Inner
	(*Optional_Inner)(nil),  // 17: types.Optional.Inner
	(*Repeated_Inner)(nil),  // 18: types.Repeated.Inner
	(*common.Imported)(nil), // 19: types.common.Imported
}
var file_types_types_proto_depIdxs = []int32{
	0,  // 0: types.EnumTypes.status:type_name -> types.Status
	1,  // 1: types.EnumTypes.priority:type_name -> types.Priority
	12, // 2: types.Maps.string_to_int:type_name -> types.Maps.StringToIntEntry
	13, // 3: types.Maps.int_to_string:type_name -> types.Maps.IntToStringEntry
	14, // 4: types.Maps.string_to_message:type_name -> types.Maps.StringToMessageEntry
	15, // 5: types.Maps.bool_to_float:type_name -> types.Maps.BoolToFloatEntry
	16, // 6: types.Oneof.inner:type_name -> types.Oneof.Inner
	19, // 7: types.Imported.imported:type_name -> types.common.Imported
	7,  // 8: types.RecursiveNode.child:type_name -> types.RecursiveNode
	7,  // 9: types.RecursiveNode.children:type_name -> types.RecursiveNode
	7,  // 10: types.Recursive.node:type_name -> types.RecursiveNode
	17, // 11: types.Optional.optional_inner:type_name -> types.Optional.Inner
	0,  // 12: types.Optional.optional_enum:type_name -> types.Status
	0,  // 13: types.Repeated.statuses:type_name -> types.Status
	18, // 14: types.Repeated.inner_items:type_name -> types.Repeated.Inner
	11, // 15: types.Maps.StringToMessageEntry.value:type_name -> types.Maps.Inner
	2,  // 16: types.TypesService.ScalarTypes:input_type -> types.ScalarTypes
	3,  // 17: types.TypesService.EnumTypes:input_type -> types.EnumTypes
	4,  // 18: types.TypesService.Maps:input_type -> types.Maps
	5,  // 19: types.TypesService.Oneof:input_type -> types.Oneof
	6,  // 20: types.TypesService.Imported:input_type -> types.Imported
	8,  // 21: types.TypesService.Recursive:input_type -> types.Recursive
	9,  // 22: types.TypesService.Optional:input_type -> types.Optional
	10, // 23: types.TypesService.Repeated:input_type -> types.Repeated
	2,  // 24: types.TypesService.ScalarTypes:output_type -> types.ScalarTypes
	3,  // 25: types.TypesService.EnumTypes:output_type -> types.EnumTypes
	4,  // 26: types.TypesService.Maps:output_type -> types.Maps
	5,  // 27: types.TypesService.Oneof:output_type -> types.Oneof
	6,  // 28: types.TypesService.Imported:output_type -> types.Imported
	8,  // 29: types.TypesService.Recursive:output_type -> types.Recursive
	9,  // 30: types.TypesService.Optional:output_type -> types.Optional
	10, // 31: types.TypesService.Repeated:output_type -> types.Repeated
	24, // [24:32] is the sub-list for method output_type
	16, // [16:24] is the sub-list for method input_type
	16, // [16:16] is the sub-list for extension type_name
	16, // [16:16] is the sub-list for extension extendee
	0,  // [0:16] is the sub-list for field type_name
}

func init() { file_types_types_proto_init() }
func file_types_types_proto_init() {
	if File_types_types_proto != nil {
		return
	}
	file_types_types_proto_msgTypes[3].OneofWrappers = []any{
		(*Oneof_Text)(nil),
		(*Oneof_Number)(nil),
		(*Oneof_Flag)(nil),
		(*Oneof_Inner_)(nil),
	}
	file_types_types_proto_msgTypes[7].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_types_types_proto_rawDesc), len(file_types_types_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   17,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_types_types_proto_goTypes,
		DependencyIndexes: file_types_types_proto_depIdxs,
		EnumInfos:         file_types_types_proto_enumTypes,
		MessageInfos:      file_types_types_proto_msgTypes,
	}.Build()
	File_types_types_proto = out.File
	file_types_types_proto_goTypes = nil
	file_types_types_proto_depIdxs = nil
}
