// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v6.33.4
// source: types/types.proto

package types

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	TypesService_ScalarTypes_FullMethodName = "/types.TypesService/ScalarTypes"
	TypesService_EnumTypes_FullMethodName   = "/types.TypesService/EnumTypes"
	TypesService_Maps_FullMethodName        = "/types.TypesService/Maps"
	TypesService_Oneof_FullMethodName       = "/types.TypesService/Oneof"
	TypesService_Imported_FullMethodName    = "/types.TypesService/Imported"
	TypesService_Recursive_FullMethodName   = "/types.TypesService/Recursive"
	TypesService_Optional_FullMethodName    = "/types.TypesService/Optional"
	TypesService_Repeated_FullMethodName    = "/types.TypesService/Repeated"
)

// TypesServiceClient is the client API for TypesService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type TypesServiceClient interface {
	ScalarTypes(ctx context.Context, in *ScalarTypes, opts ...grpc.CallOption) (*ScalarTypes, error)
	EnumTypes(ctx context.Context, in *EnumTypes, opts ...grpc.CallOption) (*EnumTypes, error)
	Maps(ctx context.Context, in *Maps, opts ...grpc.CallOption) (*Maps, error)
	Oneof(ctx context.Context, in *Oneof, opts ...grpc.CallOption) (*Oneof, error)
	Imported(ctx context.Context, in *Imported, opts ...grpc.CallOption) (*Imported, error)
	Recursive(ctx context.Context, in *Recursive, opts ...grpc.CallOption) (*Recursive, error)
	Optional(ctx context.Context, in *Optional, opts ...grpc.CallOption) (*Optional, error)
	Repeated(ctx context.Context, in *Repeated, opts ...grpc.CallOption) (*Repeated, error)
}

type typesServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewTypesServiceClient(cc grpc.ClientConnInterface) TypesServiceClient {
	return &typesServiceClient{cc}
}

func (c *typesServiceClient) ScalarTypes(ctx context.Context, in *ScalarTypes, opts ...grpc.CallOption) (*ScalarTypes, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ScalarTypes)
	err := c.cc.Invoke(ctx, TypesService_ScalarTypes_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *typesServiceClient) EnumTypes(ctx context.Context, in *EnumTypes, opts ...grpc.CallOption) (*EnumTypes, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EnumTypes)
	err := c.cc.Invoke(ctx, TypesService_EnumTypes_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *typesServiceClient) Maps(ctx context.Context, in *Maps, opts ...grpc.CallOption) (*Maps, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Maps)
	err := c.cc.Invoke(ctx, TypesService_Maps_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *typesServiceClient) Oneof(ctx context.Context, in *Oneof, opts ...grpc.CallOption) (*Oneof, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Oneof)
	err := c.cc.Invoke(ctx, TypesService_Oneof_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *typesServiceClient) Imported(ctx context.Context, in *Imported, opts ...grpc.CallOption) (*Imported, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Imported)
	err := c.cc.Invoke(ctx, TypesService_Imported_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *typesServiceClient) Recursive(ctx context.Context, in *Recursive, opts ...grpc.CallOption) (*Recursive, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Recursive)
	err := c.cc.Invoke(ctx, TypesService_Recursive_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *typesServiceClient) Optional(ctx context.Context, in *Optional, opts ...grpc.CallOption) (*Optional, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Optional)
	err := c.cc.Invoke(ctx, TypesService_Optional_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *typesServiceClient) Repeated(ctx context.Context, in *Repeated, opts ...grpc.CallOption) (*Repeated, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Repeated)
	err := c.cc.Invoke(ctx, TypesService_Repeated_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TypesServiceServer is the server API for TypesService service.
// All implementations must embed UnimplementedTypesServiceServer
// for forward compatibility.
type TypesServiceServer interface {
	ScalarTypes(context.Context, *ScalarTypes) (*ScalarTypes, error)
	EnumTypes(context.Context, *EnumTypes) (*EnumTypes, error)
	Maps(context.Context, *Maps) (*Maps, error)
	Oneof(context.Context, *Oneof) (*Oneof, error)
	Imported(context.Context, *Imported) (*Imported, error)
	Recursive(context.Context, *Recursive) (*Recursive, error)
	Optional(context.Context, *Optional) (*Optional, error)
	Repeated(context.Context, *Repeated) (*Repeated, error)
	mustEmbedUnimplementedTypesServiceServer()
}

// UnimplementedTypesServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedTypesServiceServer struct{}

func (UnimplementedTypesServiceServer) ScalarTypes(context.Context, *ScalarTypes) (*ScalarTypes, error) {
	return nil, status.Error(codes.Unimplemented, "method ScalarTypes not implemented")
}
func (UnimplementedTypesServiceServer) EnumTypes(context.Context, *EnumTypes) (*EnumTypes, error) {
	return nil, status.Error(codes.Unimplemented, "method EnumTypes not implemented")
}
func (UnimplementedTypesServiceServer) Maps(context.Context, *Maps) (*Maps, error) {
	return nil, status.Error(codes.Unimplemented, "method Maps not implemented")
}
func (UnimplementedTypesServiceServer) Oneof(context.Context, *Oneof) (*Oneof, error) {
	return nil, status.Error(codes.Unimplemented, "method Oneof not implemented")
}
func (UnimplementedTypesServiceServer) Imported(context.Context, *Imported) (*Imported, error) {
	return nil, status.Error(codes.Unimplemented, "method Imported not implemented")
}
func (UnimplementedTypesServiceServer) Recursive(context.Context, *Recursive) (*Recursive, error) {
	return nil, status.Error(codes.Unimplemented, "method Recursive not implemented")
}
func (UnimplementedTypesServiceServer) Optional(context.Context, *Optional) (*Optional, error) {
	return nil, status.Error(codes.Unimplemented, "method Optional not implemented")
}
func (UnimplementedTypesServiceServer) Repeated(context.Context, *Repeated) (*Repeated, error) {
	return nil, status.Error(codes.Unimplemented, "method Repeated not implemented")
}
func (UnimplementedTypesServiceServer) mustEmbedUnimplementedTypesServiceServer() {}
func (UnimplementedTypesServiceServer) testEmbeddedByValue()                      {}

// UnsafeTypesServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TypesServiceServer will
// result in compilation errors.
type UnsafeTypesServiceServer interface {
	mustEmbedUnimplementedTypesServiceServer()
}

func RegisterTypesServiceServer(s grpc.ServiceRegistrar, srv TypesServiceServer) {
	// If the following call panics, it indicates UnimplementedTypesServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&TypesService_ServiceDesc, srv)
}

func _TypesService_ScalarTypes_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ScalarTypes)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TypesServiceServer).ScalarTypes(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TypesService_ScalarTypes_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TypesServiceServer).ScalarTypes(ctx, req.(*ScalarTypes))
	}
	return interceptor(ctx, in, info, handler)
}

func _TypesService_EnumTypes_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EnumTypes)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TypesServiceServer).EnumTypes(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TypesService_EnumTypes_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TypesServiceServer).EnumTypes(ctx, req.(*EnumTypes))
	}
	return interceptor(ctx, in, info, handler)
}

func _TypesService_Maps_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Maps)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TypesServiceServer).Maps(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TypesService_Maps_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TypesServiceServer).Maps(ctx, req.(*Maps))
	}
	return interceptor(ctx, in, info, handler)
}

func _TypesService_Oneof_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Oneof)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TypesServiceServer).Oneof(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TypesService_Oneof_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TypesServiceServer).Oneof(ctx, req.(*Oneof))
	}
	return interceptor(ctx, in, info, handler)
}

func _TypesService_Imported_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Imported)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TypesServiceServer).Imported(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TypesService_Imported_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TypesServiceServer).Imported(ctx, req.(*Imported))
	}
	return interceptor(ctx, in, info, handler)
}

func _TypesService_Recursive_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Recursive)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TypesServiceServer).Recursive(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TypesService_Recursive_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TypesServiceServer).Recursive(ctx, req.(*Recursive))
	}
	return interceptor(ctx, in, info, handler)
}

func _TypesService_Optional_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Optional)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TypesServiceServer).Optional(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TypesService_Optional_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TypesServiceServer).Optional(ctx, req.(*Optional))
	}
	return interceptor(ctx, in, info, handler)
}

func _TypesService_Repeated_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Repeated)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TypesServiceServer).Repeated(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TypesService_Repeated_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TypesServiceServer).Repeated(ctx, req.(*Repeated))
	}
	return interceptor(ctx, in, info, handler)
}

// TypesService_ServiceDesc is the grpc.ServiceDesc for TypesService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var TypesService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "types.TypesService",
	HandlerType: (*TypesServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ScalarTypes",
			Handler:    _TypesService_ScalarTypes_Handler,
		},
		{
			MethodName: "EnumTypes",
			Handler:    _TypesService_EnumTypes_Handler,
		},
		{
			MethodName: "Maps",
			Handler:    _TypesService_Maps_Handler,
		},
		{
			MethodName: "Oneof",
			Handler:    _TypesService_Oneof_Handler,
		},
		{
			MethodName: "Imported",
			Handler:    _TypesService_Imported_Handler,
		},
		{
			MethodName: "Recursive",
			Handler:    _TypesService_Recursive_Handler,
		},
		{
			MethodName: "Optional",
			Handler:    _TypesService_Optional_Handler,
		},
		{
			MethodName: "Repeated",
			Handler:    _TypesService_Repeated_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "types/types.proto",
}
