// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: echo/echo.proto

package echo

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type EchoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Msg           string                 `protobuf:"bytes,1,opt,name=msg,proto3" json:"msg,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EchoRequest) Reset() {
	*x = EchoRequest{}
	mi := &file_echo_echo_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EchoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EchoRequest) ProtoMessage() {}

func (x *EchoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_echo_echo_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EchoRequest.ProtoReflect.Descriptor instead.
func (*EchoRequest) Descriptor() ([]byte, []int) {
	return file_echo_echo_proto_rawDescGZIP(), []int{0}
}

func (x *EchoRequest) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

type EchoResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Msg           string                 `protobuf:"bytes,1,opt,name=msg,proto3" json:"msg,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EchoResponse) Reset() {
	*x = EchoResponse{}
	mi := &file_echo_echo_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EchoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EchoResponse) ProtoMessage() {}

func (x *EchoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_echo_echo_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EchoResponse.ProtoReflect.Descriptor instead.
func (*EchoResponse) Descriptor() ([]byte, []int) {
	return file_echo_echo_proto_rawDescGZIP(), []int{1}
}

func (x *EchoResponse) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

type ErrorRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Msg           string                 `protobuf:"bytes,1,opt,name=msg,proto3" json:"msg,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ErrorRequest) Reset() {
	*x = ErrorRequest{}
	mi := &file_echo_echo_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ErrorRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ErrorRequest) ProtoMessage() {}

func (x *ErrorRequest) ProtoReflect() protoreflect.Message {
	mi := &file_echo_echo_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ErrorRequest.ProtoReflect.Descriptor instead.
func (*ErrorRequest) Descriptor() ([]byte, []int) {
	return file_echo_echo_proto_rawDescGZIP(), []int{2}
}

func (x *ErrorRequest) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

type ErrorResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Msg           string                 `protobuf:"bytes,1,opt,name=msg,proto3" json:"msg,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ErrorResponse) Reset() {
	*x = ErrorResponse{}
	mi := &file_echo_echo_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ErrorResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ErrorResponse) ProtoMessage() {}

func (x *ErrorResponse) ProtoReflect() protoreflect.Message {
	mi := &file_echo_echo_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ErrorResponse.ProtoReflect.Descriptor instead.
func (*ErrorResponse) Descriptor() ([]byte, []int) {
	return file_echo_echo_proto_rawDescGZIP(), []int{3}
}

func (x *ErrorResponse) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

type ClientStreamRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Msg           string                 `protobuf:"bytes,1,opt,name=msg,proto3" json:"msg,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClientStreamRequest) Reset() {
	*x = ClientStreamRequest{}
	mi := &file_echo_echo_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClientStreamRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientStreamRequest) ProtoMessage() {}

func (x *ClientStreamRequest) ProtoReflect() protoreflect.Message {
	mi := &file_echo_echo_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientStreamRequest.ProtoReflect.Descriptor instead.
func (*ClientStreamRequest) Descriptor() ([]byte, []int) {
	return file_echo_echo_proto_rawDescGZIP(), []int{4}
}

func (x *ClientStreamRequest) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

type ClientStreamResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Msgs          []string               `protobuf:"bytes,1,rep,name=msgs,proto3" json:"msgs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClientStreamResponse) Reset() {
	*x = ClientStreamResponse{}
	mi := &file_echo_echo_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClientStreamResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientStreamResponse) ProtoMessage() {}

func (x *ClientStreamResponse) ProtoReflect() protoreflect.Message {
	mi := &file_echo_echo_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientStreamResponse.ProtoReflect.Descriptor instead.
func (*ClientStreamResponse) Descriptor() ([]byte, []int) {
	return file_echo_echo_proto_rawDescGZIP(), []int{5}
}

func (x *ClientStreamResponse) GetMsgs() []string {
	if x != nil {
		return x.Msgs
	}
	return nil
}

type ServerStreamRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Msgs          []string               `protobuf:"bytes,1,rep,name=msgs,proto3" json:"msgs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServerStreamRequest) Reset() {
	*x = ServerStreamRequest{}
	mi := &file_echo_echo_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServerStreamRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerStreamRequest) ProtoMessage() {}

func (x *ServerStreamRequest) ProtoReflect() protoreflect.Message {
	mi := &file_echo_echo_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerStreamRequest.ProtoReflect.Descriptor instead.
func (*ServerStreamRequest) Descriptor() ([]byte, []int) {
	return file_echo_echo_proto_rawDescGZIP(), []int{6}
}

func (x *ServerStreamRequest) GetMsgs() []string {
	if x != nil {
		return x.Msgs
	}
	return nil
}

type ServerStreamResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Msg           string                 `protobuf:"bytes,1,opt,name=msg,proto3" json:"msg,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServerStreamResponse) Reset() {
	*x = ServerStreamResponse{}
	mi := &file_echo_echo_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServerStreamResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerStreamResponse) ProtoMessage() {}

func (x *ServerStreamResponse) ProtoReflect() protoreflect.Message {
	mi := &file_echo_echo_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerStreamResponse.ProtoReflect.Descriptor instead.
func (*ServerStreamResponse) Descriptor() ([]byte, []int) {
	return file_echo_echo_proto_rawDescGZIP(), []int{7}
}

func (x *ServerStreamResponse) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

type BidiStreamRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Msg           string                 `protobuf:"bytes,1,opt,name=msg,proto3" json:"msg,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BidiStreamRequest) Reset() {
	*x = BidiStreamRequest{}
	mi := &file_echo_echo_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BidiStreamRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BidiStreamRequest) ProtoMessage() {}

func (x *BidiStreamRequest) ProtoReflect() protoreflect.Message {
	mi := &file_echo_echo_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BidiStreamRequest.ProtoReflect.Descriptor instead.
func (*BidiStreamRequest) Descriptor() ([]byte, []int) {
	return file_echo_echo_proto_rawDescGZIP(), []int{8}
}

func (x *BidiStreamRequest) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

type BidiStreamResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Msg           string                 `protobuf:"bytes,1,opt,name=msg,proto3" json:"msg,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BidiStreamResponse) Reset() {
	*x = BidiStreamResponse{}
	mi := &file_echo_echo_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BidiStreamResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BidiStreamResponse) ProtoMessage() {}

func (x *BidiStreamResponse) ProtoReflect() protoreflect.Message {
	mi := &file_echo_echo_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BidiStreamResponse.ProtoReflect.Descriptor instead.
func (*BidiStreamResponse) Descriptor() ([]byte, []int) {
	return file_echo_echo_proto_rawDescGZIP(), []int{9}
}

func (x *BidiStreamResponse) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

var File_echo_echo_proto protoreflect.FileDescriptor

const file_echo_echo_proto_rawDesc = "" +
	"\n" +
	"\x0fecho/echo.proto\x12\x04echo\"\x1f\n" +
	"\vEchoRequest\x12\x10\n" +
	"\x03msg\x18\x01 \x01(\tR\x03msg\" \n" +
	"\fEchoResponse\x12\x10\n" +
	"\x03msg\x18\x01 \x01(\tR\x03msg\" \n" +
	"\fErrorRequest\x12\x10\n" +
	"\x03msg\x18\x01 \x01(\tR\x03msg\"!\n" +
	"\rErrorResponse\x12\x10\n" +
	"\x03msg\x18\x01 \x01(\tR\x03msg\"'\n" +
	"\x13ClientStreamRequest\x12\x10\n" +
	"\x03msg\x18\x01 \x01(\tR\x03msg\"*\n" +
	"\x14ClientStreamResponse\x12\x12\n" +
	"\x04msgs\x18\x01 \x03(\tR\x04msgs\")\n" +
	"\x13ServerStreamRequest\x12\x12\n" +
	"\x04msgs\x18\x01 \x03(\tR\x04msgs\"(\n" +
	"\x14ServerStreamResponse\x12\x10\n" +
	"\x03msg\x18\x01 \x01(\tR\x03msg\"%\n" +
	"\x11BidiStreamRequest\x12\x10\n" +
	"\x03msg\x18\x01 \x01(\tR\x03msg\"&\n" +
	"\x12BidiStreamResponse\x12\x10\n" +
	"\x03msg\x18\x01 \x01(\tR\x03msg2\xcf\x02\n" +
	"\vEchoService\x12/\n" +
	"\x04Echo\x12\x11.echo.EchoRequest\x1a\x12.echo.EchoResponse\"\x00\x122\n" +
	"\x05Error\x12\x12.echo.ErrorRequest\x1a\x13.echo.ErrorResponse\"\x00\x12I\n" +
	"\fClientStream\x12\x19.echo.ClientStreamRequest\x1a\x1a.echo.ClientStreamResponse\"\x00(\x01\x12I\n" +
	"\fServerStream\x12\x19.echo.ServerStreamRequest\x1a\x1a.echo.ServerStreamResponse\"\x000\x01\x12E\n" +
	"\n" +
	"BidiStream\x12\x17.echo.BidiStreamRequest\x1a\x18.echo.BidiStreamResponse\"\x00(\x010\x01B;Z9github.com/heartandu/easyrpc/internal/testdata/proto/echob\x06proto3"

var (
	file_echo_echo_proto_rawDescOnce sync.Once
	file_echo_echo_proto_rawDescData []byte
)

func file_echo_echo_proto_rawDescGZIP() []byte {
	file_echo_echo_proto_rawDescOnce.Do(func() {
		file_echo_echo_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_echo_echo_proto_rawDesc), len(file_echo_echo_proto_rawDesc)))
	})
	return file_echo_echo_proto_rawDescData
}

var file_echo_echo_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_echo_echo_proto_goTypes = []any{
	(*EchoRequest)(nil),          // 0: echo.EchoRequest
	(*EchoResponse)(nil),         // 1: echo.EchoResponse
	(*ErrorRequest)(nil),         // 2: echo.ErrorRequest
	(*ErrorResponse)(nil),        // 3: echo.ErrorResponse
	(*ClientStreamRequest)(nil),  // 4: echo.ClientStreamRequest
	(*ClientStreamResponse)(nil), // 5: echo.ClientStreamResponse
	(*ServerStreamRequest)(nil),  // 6: echo.ServerStreamRequest
	(*ServerStreamResponse)(nil), // 7: echo.ServerStreamResponse
	(*BidiStreamRequest)(nil),    // 8: echo.BidiStreamRequest
	(*BidiStreamResponse)(nil),   // 9: echo.BidiStreamResponse
}
var file_echo_echo_proto_depIdxs = []int32{
	0, // 0: echo.EchoService.Echo:input_type -> echo.EchoRequest
	2, // 1: echo.EchoService.Error:input_type -> echo.ErrorRequest
	4, // 2: echo.EchoService.ClientStream:input_type -> echo.ClientStreamRequest
	6, // 3: echo.EchoService.ServerStream:input_type -> echo.ServerStreamRequest
	8, // 4: echo.EchoService.BidiStream:input_type -> echo.BidiStreamRequest
	1, // 5: echo.EchoService.Echo:output_type -> echo.EchoResponse
	3, // 6: echo.EchoService.Error:output_type -> echo.ErrorResponse
	5, // 7: echo.EchoService.ClientStream:output_type -> echo.ClientStreamResponse
	7, // 8: echo.EchoService.ServerStream:output_type -> echo.ServerStreamResponse
	9, // 9: echo.EchoService.BidiStream:output_type -> echo.BidiStreamResponse
	5, // [5:10] is the sub-list for method output_type
	0, // [0:5] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_echo_echo_proto_init() }
func file_echo_echo_proto_init() {
	if File_echo_echo_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_echo_echo_proto_rawDesc), len(file_echo_echo_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_echo_echo_proto_goTypes,
		DependencyIndexes: file_echo_echo_proto_depIdxs,
		MessageInfos:      file_echo_echo_proto_msgTypes,
	}.Build()
	File_echo_echo_proto = out.File
	file_echo_echo_proto_goTypes = nil
	file_echo_echo_proto_depIdxs = nil
}
